Dolphin save state symlink fix
dragoonDorise/EmuDeck pull request #358
Opened 2022-08-21 02:15 UTC by DylanTackoor

Attempts to resolve https://github.com/dragoonDorise/EmuDeck/issues/355 by linking to the `StateSaves` folder for new installs and by migrating existing files from the old `states` folder to the new one. Wasn't sure if the migrate function was a good place to put this logic in, can move it elsewhere if needed 🤷

2022-08-21 02:17 UTC, DylanTackoor commented
I thought it would be cool to set Dolphin's `StateSave` directory directly, but I could only find forum threads about [it not being configurable ](https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Common/FileUtil.cpp#L959) :(

2022-08-22 06:08 UTC, Godsbane commented
what do you think about changing from saving in the .var folder to moving the save to the Emulation folder, and then using the moveSaveFolder function to move the files and link them back to the spot it's looking for?

2022-08-23 04:11 UTC, DylanTackoor commented
I initially left it under `.var` just because the `GC` and `Wii` folders were also symlinks pointing to `.var`, but yeah having the files stored under the Emulation folder feels nice. I think I've `moveSaveFolder`-ed both the folders correctly now 🤔

2022-09-03 07:14 UTC, Godsbane commented on functions/helperFunctions.sh
> +		moveSaveFolder dolphin states "$HOME/.var/app/$flatpakName/data/dolphin-emu/StateSaves"
this will not work for primehack, because it will try to link it to the Emulation/dolphin/states folder

2022-09-03 07:15 UTC, Godsbane requested changes
Please look at the migrateDolphinStates function, and make sure it works for dolphin derivatives as well by using the emuName variable.

2022-09-07 21:46 UTC, DylanTackoor commented
hah I just realized my text editor formatted a file even though I was trying to be careful about it with this PR 🤦  I'll try to revert those formatting changes later tonight tomorrow if they're annoying

2022-09-25 02:08 UTC, Godsbane approved these changes
To me this looks good.

I don't see the point of migrating states to SaveStates, because (as far as I know) there's never actually anything in states, and the link was just created to the wrong spot. That said, i like the function and think it should stay just in case.

also like the new helper function. I'm going to look at extending it a bit. I'll commit this PR to dev and we can work shop / test from there.

2022-09-25 02:11 UTC, merged